version: "3.9"

services:
  invitory_com:
    image: node:18-alpine
    container_name: invitory.com
    working_dir: /invitory.com
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=development
    volumes:
      - .:/invitory.com
    ports:
      - 5173:5173
    expose:
      - 5173
    command: tail -f docker-compose.yml